FIX: Allow wishes without host/URL set.
wishthis/wishthis pull request #202
Opened 2024-10-26 08:50 UTC by kyeno

Whenever you save a wish without an URL address and later on try to edit it, you will be greeted with plethora XHR-fetched errors. Once you rid of them and simply click on the URL field, then click away - those errors will be thrown at you again.
![wishthis errors](https://maciej.taranienko.pl/wishthis-errors.png)

**This PR aims to fix that issue.**

2024-10-26 09:18 UTC, grandeljay requested changes
Hey @kyeno,

thank you for reporting this bug and adding a working PR to it! It is highly appreciated.

While this works as a quick fix, I'd like to ask you to make some changes for better legibility:

1. Try to avoid nesting
2. Fix the cause of the issue not symptom

Since the cause is the missing URL and the symptom is a missing host, I'd like to suggest something like this:
```diff
public static function hasAffiliateLink(string $url): bool
{
+    if (empty($url)) {
+        return false;
+    }

    $urlParts = parse_url($url);

    if (isset($urlParts['query'])) {
        \parse_str($urlParts['query'], $urlParameters);
    } else {
        $urlParameters = [];
    }

    foreach (self::$affiliates as $host => $tagId) {
        if (\str_contains($urlParts['host'], $host) && isset($urlParameters['tag'])) {
            return true;
        }
    }

    return false;
}
```

2024-10-26 09:39 UTC, kyeno commented
Hey! Thanks for your reply. :)

Honestly I didn't take time to analyze if the entire `$url` was missing or just some parts of the parsed query.
I simply assumed it's the latter since `parse_url()` call itself didn't throw a notice, warning or exception.

Still I will try hard to find some extra time and take a closer look at your suggestion sometime later.

Cheers!

2024-10-26 09:43 UTC, kyeno commented
Also, please mind I'm driving this with `nginx` as a backend webserver, thus again I'd assume *some* parts of the URL will be present.

```
server {
    listen 443 ssl;
    http2 on;

    server_name *redacted*;

    root *redacted*;

    error_log *redacted*;
    access_log *redacted*;

    client_max_body_size 15m;

    # Main Wish access
    location / {

        try_files $uri /index.php$is_args$args;
    }

    # Don't create logs for favicon.ico or robots.txt requests
    location = /(?:favicon.ico|robots.txt) {
        access_log off;
        log_not_found off;
    }

    # Block hidden files
    location ~ /\. {
        deny all;
    }

    # Block access to certain JSON files
    location ~ /(?:bower|composer|jsdoc|package)\.json$ {
        deny all;
    }

    # Block access to Markdown, Twig & YAML files directly
    location ~* /(.*)\.(?:dist|markdown|md|twig|yaml|yml)$ {
        deny all;
    }

    # Enforce caching for certain file extension types
    location ~* \.(?:ico|css|js|gif|jpe?g|png|ttf|woff|woff2)$ {
        access_log off;
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public, mustrevalidate, proxy-revalidate";
    }

    # Parse PHP
    location ~ ^/index\.php(/|$) {
            include                 fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            fastcgi_param           SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param           DOCUMENT_ROOT $realpath_root;
            fastcgi_param           HTTPS           on;
            fastcgi_pass              php82;

            # Prevents URIs that include the front controller. This will 404:
            # http://domain.tld/index.php/some-path
            # Remove the internal directive to allow URIs like this
            #internal;
    }

    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }
}
```

2024-10-29 07:21 UTC, grandeljay commented
> Still I will try hard to find some extra time and take a closer look at your suggestion sometime later.

Great, thanks! If you're lacking time/motivation or whatnot, you could also just use my suggestion as it is. I thought it would be better if you submitted the changes so you can be attributed for finding and fixing the bug.

2024-10-29 09:18 UTC, kyeno commented
Hey, thanks! Literally lacking time is the issue. Also - thanks a lot for considering me. :)
I will definitely take a look into it soon, just being completely overwhelmed with work and life all of sudden.
I still think I should probably test your solution before simply commiting it - that's why I need a bit of extra time.

Love your project anyway. I wouldn't have contributed otherwise. :)

2024-12-04 14:44 UTC, grandeljay commented
Taking over since OP seems to have vanished. Fixed in https://github.com/wishthis/wishthis/commit/66d9101f3813f9915ddb38b9130cb1a1900c17fd.

2024-12-04 14:44 UTC, closed without merging